/**
 * @license
 * Copyright 2025 Damie Code
 * SPDX-License-Identifier: Apache-2.0
 */

import type { AuthType } from '../core/contentGenerator.js';

/**
 * Generate default config YAML content
 */
export function generateDefaultConfigYaml(authType: AuthType): string {
  return `# Damie Code Configuration
# Generated by Damie Code setup wizard
# Documentation: https://github.com/damoojeje/damie-code#configuration

# ============================================================================
# Security and Authentication
# ============================================================================
security:
  auth:
    # Selected authentication provider
    # Options: qwen-oauth, deepseek, openai, anthropic, openrouter, ollama
    selectedType: "${authType}"

# ============================================================================
# Provider Settings
# ============================================================================
# Configure provider-specific settings here.
# API keys can also be set via environment variables:
#   - DEEPSEEK_API_KEY
#   - OPENAI_API_KEY
#   - ANTHROPIC_API_KEY
#   - OPENROUTER_API_KEY

# providers:
#   deepseek:
#     model: "deepseek-chat"
#     # apiKey: "sk-..."  # Prefer using DEEPSEEK_API_KEY env var
#
#   openai:
#     model: "gpt-4"
#     # apiKey: "sk-..."  # Prefer using OPENAI_API_KEY env var
#
#   anthropic:
#     model: "claude-3-5-sonnet-20241022"
#     # apiKey: "sk-ant-..."  # Prefer using ANTHROPIC_API_KEY env var
#
#   openrouter:
#     model: "anthropic/claude-3.5-sonnet"
#     # apiKey: "sk-or-..."  # Prefer using OPENROUTER_API_KEY env var
#
#   ollama:
#     baseUrl: "http://localhost:11434"
#     model: "llama3.1"
#     keepAlive: "5m"

# ============================================================================
# Model Settings
# ============================================================================
model:
  # Enable chat compression for long conversations
  chatCompression: true

  # Maximum tokens per response
  # maxTokens: 4096

  # Task-based routing (optional)
  # Route different task types to different providers
  # routing:
  #   coding: deepseek      # Use DeepSeek for coding tasks
  #   reasoning: anthropic  # Use Claude for reasoning
  #   general: openai       # Use GPT-4 for general tasks

# ============================================================================
# UI Settings
# ============================================================================
ui:
  # Theme name (default, dark, light, or custom)
  # theme: "default"

  # Hide tips and suggestions
  hideTips: false

  # Hide startup banner
  hideBanner: false

  # Show line numbers in code blocks
  showLineNumbers: true

# ============================================================================
# Advanced Settings
# ============================================================================
# For more advanced configuration options, see the documentation.
`;
}

/**
 * Generate minimal config YAML for a provider
 */
export function generateMinimalConfigYaml(
  authType: AuthType,
  model?: string,
): string {
  const lines = [
    '# Damie Code Configuration',
    '# Generated by setup wizard',
    '',
    'security:',
    '  auth:',
    `    selectedType: "${authType}"`,
  ];

  if (model) {
    lines.push('');
    lines.push('model:');
    lines.push(`  default: "${model}"`);
  }

  lines.push('');

  return lines.join('\n');
}
