/**
 * @license
 * Copyright 2025 Damie Code
 * SPDX-License-Identifier: Apache-2.0
 */

import * as fs from 'node:fs';
import { AuthType } from '@damie-code/damie-code-core';
import { getDamieConfigDir, getDamieConfigPath, ensureConfigDir } from './firstRunDetector.js';
import type { SetupConfig } from './types.js';
import { getProviderInfo } from './types.js';

/**
 * Generate YAML config content from setup config (supports multiple providers)
 */
function generateConfigYaml(
  configs: Array<{ provider: AuthType; apiKey?: string; model?: string }>,
  primaryProvider: AuthType,
): string {
  const lines: string[] = [
    '# Damie Code Configuration',
    '# Generated by setup wizard',
    '',
    '# Security and authentication settings',
    'security:',
    '  auth:',
    `    selectedType: "${primaryProvider}"  # Primary provider`,
    '',
    '  # Multiple providers configured for intelligent routing:',
  ];
  
  configs.forEach(({ provider }) => {
    const info = getProviderInfo(provider);
    lines.push(`  # - ${info?.name || provider}`);
  });

  // Add provider-specific settings for each configured provider
  configs.forEach(({ provider, apiKey, model }) => {
    const info = getProviderInfo(provider);
    const providerKey = provider.replace('USE_', '').toLowerCase();
    
    lines.push('');
    lines.push(`# ${info?.name || provider} settings`);
    lines.push(`${providerKey}:`);
    
    if (apiKey && info?.envVar) {
      lines.push(`  apiKey: env:${info.envVar}  # Set via environment`);
    }
    
    if (model) {
      lines.push(`  model: "${model}"`);
    } else if (provider === AuthType.USE_OLLAMA) {
      lines.push('  model: "llama3.1"  # Default model');
      lines.push('  baseUrl: "http://localhost:11434"');
    } else if (provider === AuthType.USE_OPENROUTER) {
      lines.push('  model: "openai/gpt-4o"  # Default model');
      lines.push('  baseUrl: "https://openrouter.ai/api/v1"');
    } else if (provider === AuthType.USE_DEEPSEEK) {
      lines.push('  model: "deepseek-chat"  # or "deepseek-coder"');
    } else if (provider === AuthType.USE_ANTHROPIC) {
      lines.push('  model: "claude-3-5-sonnet-20241022"');
    } else if (provider === AuthType.USE_OPENAI) {
      lines.push('  model: "gpt-4o"');
    }
  });

  // Add model routing configuration
  lines.push('');
  lines.push('# Model routing - automatic provider selection based on task type');
  lines.push('model:');
  lines.push('  routing:');
  lines.push('    coding: "deepseek"     # Code generation');
  lines.push('    reasoning: "anthropic" # Logical reasoning');
  lines.push('    general: "deepseek"    # General tasks');
  lines.push('    vision: "openai"       # Image analysis');
  lines.push('');
  lines.push('  # chatCompression: true  # Compress long conversations');
  lines.push('  # maxTokens: 4096  # Max tokens per response');

  // Add UI settings
  lines.push('');
  lines.push('# UI settings');
  lines.push('ui:');
  lines.push('  # theme: "default"  # Theme name');
  lines.push('  # hideTips: false  # Hide tips');
  lines.push('  # hideBanner: false  # Hide startup banner');

  // Add helpful comments
  lines.push('');
  lines.push('# For more configuration options, see:');
  lines.push('# https://github.com/damoojeje/damie-code#configuration');

  return lines.join('\n') + '\n';
}

/**
 * Write the configuration to the config file (supports multiple providers)
 */
export async function writeConfig(
  configs: Array<{ provider: AuthType; apiKey?: string; model?: string }>,
  primaryProvider: AuthType,
): Promise<string> {
  ensureConfigDir();

  const configPath = getDamieConfigPath();
  const yamlContent = generateConfigYaml(configs, primaryProvider);

  fs.writeFileSync(configPath, yamlContent, 'utf8');

  // Also set environment variables for all provided API keys
  configs.forEach(({ provider, apiKey }) => {
    if (apiKey) {
      const providerInfo = getProviderInfo(provider);
      if (providerInfo?.envVar) {
        // Write to .env file in config directory for persistence
        const envPath = `${getDamieConfigDir()}/.env`;
        const envContent = `${providerInfo.envVar}=${apiKey}\n`;

        // Append or create .env file
        if (fs.existsSync(envPath)) {
          const existingContent = fs.readFileSync(envPath, 'utf8');
          // Check if variable already exists
          const regex = new RegExp(`^${providerInfo.envVar}=.*$`, 'm');
          if (regex.test(existingContent)) {
            // Replace existing
            const newContent = existingContent.replace(regex, `${providerInfo.envVar}=${apiKey}`);
            fs.writeFileSync(envPath, newContent, 'utf8');
          } else {
            // Append
            fs.appendFileSync(envPath, envContent);
          }
        } else {
          fs.writeFileSync(envPath, envContent, 'utf8');
        }

        // Set for current session
        process.env[providerInfo.envVar] = apiKey;
      }
    }
  });

  return configPath;
}

/**
 * Read existing config if any
 */
export function readConfig(): SetupConfig | null {
  const configPath = getDamieConfigPath();

  if (!fs.existsSync(configPath)) {
    return null;
  }

  try {
    const content = fs.readFileSync(configPath, 'utf8');
    // Simple YAML parsing for the auth type
    const match = content.match(/selectedType:\s*"?([^"\n]+)"?/);
    if (match) {
      return {
        provider: match[1] as AuthType,
      };
    }
  } catch (_error) {
    // Ignore read errors
  }

  return null;
}
